HealthCheck:
  handler: src/functions/healthCheck.handler
  name: healthCheck
  events:
    - http:
        method: get
        path: /
        cors: true

Playground:
  handler: src/functions/playground.handler
  name: player
  events:
    - http:
        method: post
        path: /playground
        cors: true

Sync:
  handler: src/functions/syncClickupJira.handler
  name: syncer
  events:
    # - schedule: rate(2 hours)
    - http:
        method: get
        path: /sync
        cors: true

CreateVapiPhone:
  handler: src/functions/vapiSetPhones.handler
  name: vapiCreater
  events:
    - http:
        method: post
        path: /createVapiPhone
        cors: true

DeleteVapiPhone:
  handler: src/functions/vapiDeleteAllPhones.handler
  name: vapiDeleter
  events:
    - http:
        method: post
        path: /deleteVapiPhones
        cors: true

DeleteTwilioPhone:
  handler: src/functions/twilioDeleteAllPhones.handler
  name: twilioDeleter
  events:
    - http:
        method: post
        path: /deleteTwilioPhones
        cors: true