HealthCheck:
  handler: src/functions/healthCheck.handler
  name: healthCheck
  events:
    - http:
        method: get
        path: /
        cors: true

Sync:
  handler: src/functions/syncClickupJira.handler
  name: syncer
  events:
    - schedule: rate(2 hours)
    - http:
        method: get
        path: /sync
        cors: true

CreatePhone:
  handler: src/functions/vapiSetPhones.handler
  name: creater
  events:
    - http:
        method: post
        path: /createPhone
        cors: true

Playground:
  handler: src/functions/playground.handler
  name: player
  events:
    - http:
        method: post
        path: /playground
        cors: true