HealthCheck:
  handler: src/functions/healthCheck.handler
  name: healthCheck
  events:
    - http:
        method: get
        path: /
        cors: true

Sync:
  handler: src/functions/syncClickupJira.handler
  name: syncer
  events:
    - schedule: rate(2 hours)
    - http:
        method: get
        path: /sync
        cors: true